### ISSUE TITLE
the redis php7 file link is broken

### ISSUE THREAD

**Issue by blatherdrift** [in3rsha/bitcoin-to-neo4j#14]
hey 

i cant find the right file please advise? :) 

Thanks

**Comment by brunoaduarte** [comment]
> hey
> 
> i cant find the right file please advise? :)
> 
> Thanks

If you're on Ubuntu just install it using APT
Just execute this line and install most of the needed packages

`sudo apt install php7.2 php7.2-dev php7.2-gmp php7.2-curl php7.2-bcmath php7.2-mbstring redis php-redis`
