### ISSUE TITLE
Neo4j client errors on start

### ISSUE THREAD

**Issue by sudotralex** [in3rsha/bitcoin-to-neo4j#17]
PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /root/bitcoin-to-neo4j/main.php on line 92
PHP Warning:  feof() expects parameter 1 to be resource, boolean given in /root/bitcoin-to-neo4j/main.php on line 153
PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /root/bitcoin-to-neo4j/main.php on line 92

any help would be appreciated on this error

**Comment by in3rsha** [comment]
Do you have the bitcoin blockchain downloaded? The script reads the `blk.dat` files that bitcoin core downloads as it syncs up with the blockchain.
