### ISSUE TITLE
updating to neo4j 4 

### ISSUE THREAD

**Issue by bbm-design** [in3rsha/bitcoin-to-neo4j#24]
While trying to update to neo4j 4 i faced one major incompatibility at

`        // a. Create the new block, or add properties to it if we've already made a placeholder for it.
        $createblock = "
        MERGE (block:block {hash:'$blockhash'})
        CREATE UNIQUE (block)-[:coinbase]->(:output:coinbase)
        SET
            block.size=$blocksize,
            block.txcount=$txcount,
            block.version=$version,
            block.prevblock='$prevblock',
            block.merkleroot='$merkleroot',
            block.time=$timestamp,
            block.bits='$bits',
            block.nonce=$nonce
        ";`

the error is saying 

`Invalid input 'UNIQUE': expected "shortestPath", "allShortestPaths" or "(" (line 3, column 24 (offset: 118))
"        CREATE UNIQUE (block)-[:coinbase]->(:output:coinbase)"
                ^ in /media/mdb/storage/btc/bitcoin-to-neo4j-master/vendor/plumtreesystems/neo4j-php-client/src/Connection/Connection.php:119
`
Trying to understand the role of The UNIQUE and what you are trying to avoid with it, so i can update the code accordingly 

During the update, i had to try/catch over the CONSTRAINT creation, as neo4j 4 is less permissive when trying to create constraint that already exist.

Will push the branch once i'm done updating

**Comment by bbm-design** [comment]
Updated it with merge, should be working, but need a confirmation over it

**Comment by in3rsha** [comment]
Thanks. I haven't tested this code in a while, but from first glance it doesn't seem that the `UNIQUE` part is necessary. Does it run without errors if you just take the `UNIQUE` part out?

-----

ASIDE: It's not unexpected to be seeing empty nodes (they should be attached to outputs). If I remember correctly the nodes with no label are a side-effect if this Cypher query:

```
FOREACH (output in [$outputs] |
MERGE (out :output {index: output.index})
MERGE (tx)-[:out {vout: output.vout}]->(out)
FOREACH(ignoreMe IN CASE WHEN output.addresses <> '' THEN [1] ELSE [] END |
	MERGE (address :address {address: output.addresses})
	MERGE (out)-[:locked]->(address)
)

MERGE (out)-[:in]->(existing)
ON CREATE SET
	out.value= output.value,
	out.scriptPubKey= output.scriptPubKey
ON MATCH SET
	out.value= output.value,
	out.scriptPubKey= output.scriptPubKey,
	existing.fee = existing.fee + output.value

)
```

I think it was something to do with updating the current fee on a transaction using existing inputs. This was the only thing I didn't manage to solve when I was working on this.

**Comment by bbm-design** [comment]
i simply used merge and it worked like a charm, as merge is the most logical replacement of create unique and as i feared duplication.

Do you have by any mean a torrent version of the actual db, i want to try the merge performance on a larger scale

**Comment by in3rsha** [comment]
Thanks, much appreciated.

I haven't got a torrent working yet I'm afraid.

**Comment by in3rsha** [comment]
#25
