### ISSUE TITLE
Error when trying to install phpredis

### ISSUE THREAD

**Issue by 540gyro** [in3rsha/bitcoin-to-neo4j#6]
I get the following error when I'm entering the command: sudo wget https://github.com/phpredis/phpredis/archive/php7.zip

--2018-07-30 00:18:15--  https://github.com/phpredis/phpredis/archive/php7.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/phpredis/phpredis/zip/php7 [following]
--2018-07-30 00:18:15--  https://codeload.github.com/phpredis/phpredis/zip/php7
Resolving codeload.github.com (codeload.github.com)... 192.30.253.120, 192.30.253.121
Connecting to codeload.github.com (codeload.github.com)|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-07-30 00:18:21 ERROR 404: Not Found.

Thanks in advance!

**Comment by in3rsha** [comment]
Lately I've just been installing it via `sudo apt install php-redis`. Haven't had any problems with it and is much easier than installing manually.

It's available via the PHP PPA: https://launchpad.net/%7Eondrej/+archive/ubuntu/php

**Comment by 540gyro** [comment]
Due to the multiple errors I was getting I wrote a new guide for this script which worked and started importing bitcoin blockchain on neo4j. The db got big enough though and since I was running it on lab's pc gave up.

I haven't run the guide a couple of months now so I'm not sure if it still works.

@in3rsha if you want you can take a look and post it in case it does the job.
