### ISSUE TITLE
make: *** No rule to make target `geohash-int'.  Stop.

### ISSUE THREAD

**Issue by 540gyro** [in3rsha/bitcoin-to-neo4j#7]
When running the following command:

sudo make geohash-int jemalloc lua hiredis linenoise

I get the following error:

make: *** No rule to make target `geohash-int'.  Stop.

I run ls to see the files in the directory:

Makefile                README.md               hiredis                 jemalloc                linenoise               lua                     update-jemalloc.sh

*** Operating system: Mac Os High Sierra

**Comment by brunoaduarte** [comment]
```
ubuntu@vboxubuntu:/usr/local/share/redis-stable/deps$ sudo ./configure
sudo: ./configure: command not found
```

**Comment by in3rsha** [comment]
Thanks @brunoaduarte.

Also, for anyone on Ubuntu, it's easier to install Redis with 

```
sudo apt install redis
```
