### ISSUE TITLE
Where does redis store the settings below?

### ISSUE THREAD

**Issue by 540gyro** [in3rsha/bitcoin-to-neo4j#8]
What is the directory redis stores the info below?

redis-cli hgetall bitcoin-to-neo4j
redis-cli hgetall bitcoin-to-neo4j:orphans
redis-cli hgetall bitcoin-to-neo4j:tip

**Comment by in3rsha** [comment]
Probably `/var/lib/redis`. Never had to access it myself though.

https://stackoverflow.com/questions/32284494/where-is-the-data-directory-in-redis

**Comment by brunoaduarte** [comment]
If you want to reset the import just do
```
ubuntu@vboxubuntu:~$ redis-cli
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379>
```

**Comment by in3rsha** [comment]
@brunoaduarte Yes, quite right, thank you. This will reset the file name and file pointer for where the import is currently at.

However, `FLUSHALL` will also delete any data you have stored in Redis from other programs. So to **delete the bitcoin-to-neo4j data only**:

```
$ redis-cli del bitcoin-to-neo4j
$ redis-cli del bitcoin-to-neo4j:tip
$ redis-cli del bitcoin-to-neo4j:orphans
$ redis-cli del bitcoin-to-neo4j:log
``` 

Or in one line:

```
$ redis-cli del bitcoin-to-neo4j && redis-cli del bitcoin-to-neo4j:tip && redis-cli del bitcoin-to-neo4j:orphans && redis-cli del bitcoin-to-neo4j:log
```
